### ISSUE TITLE
Tracks doesn't load

### ISSUE THREAD

**Issue by ptgms** [rasmuslos/AmpFin#3]
The tracks view doesn't load and fails even when connected to internet. Everything else works
![image](https://github.com/rasmuslos/music/assets/62300763/12c1068b-81d2-4761-a1bc-bd29ca9e570b)

**Comment by ptgms** [comment]
Album artists and artists seem to have same issue

**Comment by rasmuslos** [comment]
What server version are you using, and can you provide logs (shown in the Xcode console)?

**Comment by rasmuslos** [comment]
Try the latest version, it should fix the artist relates issues https://github.com/rasmuslos/music/releases/tag/v1.0.6

**Comment by ptgms** [comment]
Will try! Sorry for not taking lots - was busy with work

**Comment by ptgms** [comment]
Artists work now - tracks still don't. Will take logs the second I get a chance

**Comment by ptgms** [comment]
https://jellyfin.SERVER.URL/Users/XYZ/Items?SortBy=DateCreated,SortName&SortOrder=Ascending&IncludeItemTypes=Audio&Recursive=true&ImageTypeLimit=1&EnableImageTypes=Primary&Fields=AudioInfo,ParentId: The data couldn’t be read because it is missing.
This is the error

**Comment by rasmuslos** [comment]
It probably is a JSON error, there should be another message below this one, it has a white background

<img width="818" alt="Bildschirmfoto 2023-10-29 um 11 10 34" src="https://github.com/rasmuslos/AmpFin/assets/49640416/32a79ab7-5614-41e0-8dc2-5e07245b2564">

**Comment by rasmuslos** [comment]
I was already aware of a bug that occurred when a track was is not properly identified by the server, resulting in the name of the album being blank. I just ignored it assuming it was a me issue, but apparently it is more widespread. If the [latest release](https://github.com/rasmuslos/AmpFin/releases/tag/v1.0.7) makes it work for you, could you check your library for an album that is not properly imported (missing artist, tracks out of order, missing track number, etc.)

**Comment by ptgms** [comment]
I can't check I have SO many albums on my server hahaha. Latest release works though. Feel free to close the issue :) I'll keep it open just in case otherwise.
