### ISSUE TITLE
incorrectly showing artists when artist.seperator is used

### ISSUE THREAD

**Issue by szaszlyki21** [rasmuslos/AmpFin#5]
I've noticed that in the new build 1.0.8 tracks with multiple artists now shows the separator incorrectly as shown in the picture
![IMG_2529](https://github.com/rasmuslos/AmpFin/assets/96011540/f9a4129e-d9d1-4491-99a8-26adcce2a657)

**Comment by rasmuslos** [comment]
Thank you for finding this, it is fixed in the latest version https://github.com/rasmuslos/AmpFin/releases/tag/v1.0.9

**Comment by szaszlyki21** [comment]
Unfortunately, the issue still persist in the latest update. I've checked with the official client just to be sure and yes it does show the artists correctly on the ios client. 
![IMG_2545](https://github.com/rasmuslos/AmpFin/assets/96011540/edb00287-348a-40ab-b43e-a5a8e99cfdd3)
![IMG_2544](https://github.com/rasmuslos/AmpFin/assets/96011540/745552e7-23da-4582-865b-08093e13916b)
